{{ if (include "authelia.enabled.ingress.traefik" .) -}}
{{- range $name, $endpoint := (include "authelia.authz" .) | fromJson }}
{{- if eq $endpoint.implementation "ForwardAuth" }}
---
apiVersion: {{ include "capabilities.apiVersion.traefik.Middleware" $ }}
kind: Middleware
metadata:
  name: {{ include "authelia.ingress.traefikCRD.middleware.forwardAuth.name" (merge (dict "Name" $name) $) }}
  labels: {{ include "authelia.labels" $ | nindent 4 }}
  {{- with $annotations := include "authelia.annotations" $ }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
spec:
  forwardAuth:
    address: {{ (include "authelia.ingress.traefikCRD.middleware.forwardAuth.address" (merge (dict "Name" $name) $)) | squote }}
    trustForwardHeader: true
    {{- with $.Values.ingress.traefikCRD.middlewares.auth.authResponseHeaders }}
    authResponseHeaders:
    {{- range . }}
    - {{ . | squote }}
    {{- end }}
  {{- end }}
---
apiVersion: {{ include "capabilities.apiVersion.traefik.Middleware" $ }}
kind: Middleware
metadata:
  name: {{ include "authelia.ingress.traefikCRD.middleware.chainAuth.name" (merge (dict "Name" $name) $) }}
  labels: {{ include "authelia.labels" $ | nindent 4 }}
  {{- with $annotations := include "authelia.annotations" $ }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
spec:
  chain:
    middlewares:
    {{- range $middleware := $.Values.ingress.traefikCRD.middlewares.chains.auth.before }}
      - name: {{ $middleware.name }}
        {{- if $middleware.namespace }}
        namespace: {{ $middleware.namespace }}
        {{- end }}
    {{- end }}
      - name: {{ include "authelia.ingress.traefikCRD.middleware.forwardAuth.name" (merge (dict "Name" $name) $) }}
        namespace: {{ $.Release.Namespace }}
    {{- range $middleware := $.Values.ingress.traefikCRD.middlewares.chains.auth.after }}
      - name: {{ $middleware.name }}
        {{- if $middleware.namespace }}
        namespace: {{ $middleware.namespace }}
        {{- end }}
    {{- end }}
{{- end }}
{{- end }}
---
apiVersion: {{ include "capabilities.apiVersion.traefik.Middleware" . }}
kind: Middleware
metadata:
  name: {{ printf "headers-%s" (include "authelia.name" .) }}
  labels: {{ include "authelia.labels" . | nindent 4 }}
  {{- with $annotations := include "authelia.annotations" . }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
spec:
  headers:
    browserXssFilter: true
    customFrameOptionsValue: "SAMEORIGIN"
    customResponseHeaders:
      Cache-Control: "no-store"
      Pragma: "no-cache"
---
apiVersion: {{ include "capabilities.apiVersion.traefik.Middleware" . }}
kind: Middleware
metadata:
  name: {{ include "authelia.ingress.traefikCRD.middleware.chainIngress.name" . }}
  labels:
  {{- include "authelia.labels" . | nindent 4 }}
  {{- with $annotations := (include "authelia.annotations" .) }}
  annotations:
  {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  chain:
    middlewares:
    {{- range $middleware := .Values.ingress.traefikCRD.middlewares.chains.ingressRoute.before }}
      - name: {{ $middleware.name }}
        {{- if $middleware.namespace }}
        namespace: {{ $middleware.namespace }}
        {{- end }}
    {{- end }}
      - name: {{ printf "headers-%s" (include "authelia.name" .) }}
        namespace: {{ .Release.Namespace }}
    {{- range $middleware := .Values.ingress.traefikCRD.middlewares.chains.ingressRoute.after }}
      - name: {{ $middleware.name }}
        {{- if $middleware.namespace }}
        namespace: {{ $middleware.namespace }}
        {{- end }}
    {{- end }}
{{- end -}}