{{ if (include "authelia.enabled.ingress.traefik" .) -}}
---
apiVersion: {{ include "capabilities.apiVersion.traefikCRD" . }}
kind: Middleware
metadata:
  name: {{ include "authelia.ingress.traefikCRD.middleware.name.forwardAuth" . }}
  labels: {{ include "authelia.labels" . | nindent 4 }}
  {{- with $annotations := include "authelia.annotations" . }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
spec:
  forwardAuth:
    address: {{ (include "authelia.forwardAuthPath" .) }}
    trustForwardHeader: true
    {{- with .Values.ingress.traefikCRD.middlewares.auth.authResponseHeaders }}
    authResponseHeaders: {{- toYaml . | nindent 6 }}
  {{- end }}
---
apiVersion: {{ include "capabilities.apiVersion.traefikCRD" . }}
kind: Middleware
metadata:
  name: {{ printf "headers-%s" (include "authelia.name" .) }}
  labels: {{ include "authelia.labels" . | nindent 4 }}
  {{- with $annotations := include "authelia.annotations" . }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
spec:
  headers:
    browserXssFilter: true
    customFrameOptionsValue: "SAMEORIGIN"
    customResponseHeaders:
      Cache-Control: "no-store"
      Pragma: "no-cache"
---
apiVersion: {{ include "capabilities.apiVersion.traefikCRD" . }}
kind: Middleware
metadata:
  name: {{ include "authelia.ingress.traefikCRD.middleware.name.chainAuth" . }}
  labels: {{ include "authelia.labels" . | nindent 4 }}
  {{- with $annotations := include "authelia.annotations" . }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
spec:
  chain:
    middlewares:
      {{- with $middlewares := .Values.ingress.traefikCRD.middlewares.chains.auth.before }}
      {{- toYaml $middlewares | nindent 6 }}
      {{- end }}
      - name: {{ include "authelia.ingress.traefikCRD.middleware.name.forwardAuth" . }}
        namespace: {{ .Release.Namespace }}
  {{- with $middlewares := .Values.ingress.traefikCRD.middlewares.chains.auth.after }}
  {{- toYaml $middlewares | nindent 6 }}
  {{- end }}
---
apiVersion: {{ include "capabilities.apiVersion.traefikCRD" . }}
kind: Middleware
metadata:
  name: {{ include "authelia.ingress.traefikCRD.middleware.name.chainIngress" . }}
  labels:
  {{- include "authelia.labels" . | nindent 4 }}
  {{- with $annotations := (include "authelia.annotations" .) }}
  annotations:
  {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  chain:
    middlewares:
      {{- with $middlewares := .Values.ingress.traefikCRD.middlewares.chains.ingressRoute.before }}
      {{- toYaml $middlewares | nindent 6 }}
      {{- end }}
      - name: {{ printf "headers-%s" (include "authelia.name" .) }}
        namespace: {{ .Release.Namespace }}
  {{- with $middlewares := .Values.ingress.traefikCRD.middlewares.chains.ingressRoute.after }}
  {{- toYaml $middlewares | nindent 6 }}
  {{- end }}
{{- end -}}