{{ .Name }}:
  implementation: {{ .Endpoint.implementation | squote }}
  {{- with $strategies := .Endpoint.authn_strategies }}
  authn_strategies:
  {{- range $strategy := $strategies }}
    - name: {{ $strategy.name | squote }}
      {{- with $schemes := $strategy.schemes }}
      schemes:
      {{- range $schemes }}
      - {{ . | squote }}
      {{- end }}
      {{- end }}
      {{- if semverCompare ">=4.39.0" (include "authelia.version" $) }}
      scheme_basic_cache_lifespan: {{ $strategy.scheme_basic_cache_lifespan | default 0 }}
      {{- end }}
  {{- end }}
  {{- end }}