env:
  CR_BYPASS: ${CR_BYPASS}
  CT_BYPASS: ${CT_BYPASS}

steps:
- command: "ct --config .buildkite/ct.version.yaml lint"
  label: ":helm: Chart Version (Chart Testing)"
  agents:
    charts: "true"
  if: build.branch != "gh-pages"

- command: "ct --config .buildkite/ct.yaml lint"
  label: ":helm: Linting (Chart Testing)"
  agents:
    charts: "true"
  if: build.branch != "gh-pages"

- wait: ~
  continue_on_failure: true

- commands:
  - "mkdir .cr-release-packages"
  - "ct --config .buildkite/ct.yaml list-changed | xargs -n1 cr --config .buildkite/cr.yaml package"
  label: ":package: Package Chart (Chart Releaser)"
  artifact_paths:
  - ".cr-release-packages/*"
  agents:
    charts: "true"
  if: build.branch == "master" && build.env("CR_BYPASS") != "true"

- commands:
  - "mkdir .cr-release-packages"
  - "buildkite-agent artifact download .cr-release-packages/* .cr-release-packages"
  - "cr --config .buildkite/cr.yaml upload"
  label: ":github: Deploy Artifacts (Chart Releaser)"
  agents:
    charts: "true"
  depends_on:
  - step: ":package: Package Chart (Chart Releaser)"
  if: build.branch == "master" && build.env("CR_BYPASS") != "true"

- commands:
  - "mkdir .cr-release-packages .cr-index"
  - "buildkite-agent artifact download .cr-release-packages/* .cr-release-packages"
  - "git branch -d gh-pages"
  - "cr --config .buildkite/cr.yaml index --push"
  label: ":k8s: Publish Chart Index (Chart Releaser)"
  agents:
    charts: "true"
  depends_on:
  - step: ":github: Deploy Artifacts (Chart Releaser)"
  if: build.branch == "master" && build.env("CR_BYPASS") != "true"
