env:
  CHART_CHANGES: ${CHART_CHANGES}

steps:
- command: "ct --config .buildkite/ct.version.yaml lint"
  key: "lint-version"
  label: ":helm: Chart Version (Chart Testing)"
  agents:
    charts: "true"
  if: build.branch != "gh-pages" && build.env("CHART_CHANGES") == "true"

- command: "ct --config .buildkite/ct.yaml lint"
  key: "lint"
  label: ":helm: Linting (Chart Testing)"
  agents:
    charts: "true"
  if: build.branch != "gh-pages" && build.env("CHART_CHANGES") == "true"

- command: "ct --config .buildkite/ct.yaml list-changed --since HEAD~1 | xargs -n1 cr --config .buildkite/cr.yaml package"
  key: "package-test"
  label: ":package: Package Chart (Chart Releaser)"
  artifact_paths:
    - ".cr-release-packages/*"
  agents:
    charts: "true"
  if: build.branch != "gh-pages" && build.branch != "master" && build.env("CHART_CHANGES") == "true"

- wait: ~
  continue_on_failure: true
  if: build.branch == "master" && build.env("CHART_CHANGES") == "true"

- command: "ct --config .buildkite/ct.yaml list-changed --since HEAD~1 | xargs -n1 cr --config .buildkite/cr.yaml package"
  key: "package"
  label: ":package: Package Chart (Chart Releaser)"
  artifact_paths:
  - ".cr-release-packages/*"
  agents:
    charts: "true"
  if: build.branch == "master" && build.env("CHART_CHANGES") == "true"

- command: "cr --config .buildkite/cr.yaml upload  --auto-release"
  key: "upload"
  label: ":github: Deploy Artifacts (Chart Releaser)"
  agents:
    charts: "true"
  depends_on:
  - step: "package"
  if: build.branch == "master" && build.env("CHART_CHANGES") == "true"

- command: "cr --config .buildkite/cr.yaml index --push"
  key: "index"
  label: ":k8s: Publish Chart Index (Chart Releaser)"
  agents:
    charts: "true"
  depends_on:
  - step: "upload"
  if: build.branch == "master" && build.env("CHART_CHANGES") == "true"
