env:
  CR_BYPASS: ${CR_BYPASS}

steps:
  - label: ":helm: Linting (Chart Testing)"
    command: "ct --config .buildkite/ct.yaml lint"
    agents:
      charts: "true"
    if: build.branch != "gh-pages"
  
  - label: ":package: Package Chart (Chart Releaser)"
    commands:
      - "mkdir .cr-release-packages .cr-index"
      - "ct --config .buildkite/ct.yaml list-changed | xargs -n1 cr --config .buildkite/cr.yaml package"
    artifact_paths:
      - ".cr-release-packages/*"
    agents:
      charts: "true"
    if: build.branch == "master" && build.env("CR_BYPASS") != "true"
  
  - label: ":github: Deploy Artifacts (Chart Releaser)"
    commands:
      - "buildkite-agent artifact download .cr-release-packages/* .cr-release-packages"
      - "cr --config .buildkite/cr.yaml upload"
    agents:
      charts: "true"
    if: build.branch == "master" && build.env("CR_BYPASS") != "true"
  
  - label: ":k8s: Publish Chart Index (Chart Releaser)"
    commands:
      - "buildkite-agent artifact download .cr-release-packages/* .cr-release-packages"
      - "cr --config .buildkite/cr.yaml index --push"
    agents:
      charts: "true"
    if: build.branch == "master" && build.env("CR_BYPASS") != "true"
