env:
  CHART_CHANGES: ${CHART_CHANGES}

steps:
- command: "ct --config .buildkite/ct.version.yaml lint"
  key: "lint-version"
  label: ":helm: Chart Version (Chart Testing)"
  agents:
    charts: "true"
  if: build.branch != "gh-pages"

- command: "ct --config .buildkite/ct.yaml lint"
  key: "lint"
  label: ":helm: Linting (Chart Testing)"
  agents:
    charts: "true"
  if: build.branch != "gh-pages"

- wait: ~
  continue_on_failure: true

- commands:
  - "mkdir .cr-release-packages"
  - "ct --config .buildkite/ct.yaml list-changed | xargs -n1 cr --config .buildkite/cr.yaml package"
  key: "package"
  label: ":package: Package Chart (Chart Releaser)"
  artifact_paths:
  - ".cr-release-packages/*"
  agents:
    charts: "true"
  if: build.branch == "master" && build.env("CHART_CHANGES") == "true"

- commands:
  - "mkdir .cr-release-packages"
  - "buildkite-agent artifact download .cr-release-packages/* .cr-release-packages"
  - "cr --config .buildkite/cr.yaml upload"
  key: "upload"
  label: ":github: Deploy Artifacts (Chart Releaser)"
  agents:
    charts: "true"
  depends_on:
  - step: "package"
  if: build.branch == "master" && build.env("CHART_CHANGES") == "true"

- block: "Pre-index Block"
  key: "block"
  depends_on:
  - step: "upload"
  if: build.branch == "master" && build.env("CHART_CHANGES") == "true"

- commands:
  - "sleep 120"
  - "buildkite-agent artifact download .cr-release-packages/* .cr-release-packages"
  - "sleep 120"
  - "cr --config .buildkite/cr.yaml index --push"
  key: "index"
  label: ":k8s: Publish Chart Index (Chart Releaser)"
  agents:
    charts: "true"
  depends_on:
  - step: "block"
  if: build.branch == "master" && build.env("CHART_CHANGES") == "true"
