{{- if (include "authelia.enabled.podDisruptionBudget" .) }}
---
apiVersion: {{ include "capabilities.apiVersion.podDisruptionBudget" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "authelia.name" . }}
  labels: {{ include "authelia.labels" (merge (dict "Labels" .Values.podDisruptionBudget.labels) .) | nindent 4 }}
  {{- with $annotations := include "authelia.annotations" (merge (dict "Labels" .Values.podDisruptionBudget.annotations) .) }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else }}
  minAvailable: 1
  {{- end }}
  selector:
    matchLabels: {{- include "authelia.matchLabels" . | nindent 6 }}
{{- end -}}