{{- if and (include "authelia.enabled.acl.secret" .) (not .Values.configMap.access_control.secret.existingSecret) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ printf "%s-acl" (include "authelia.name" .) }}
  labels: {{ include "authelia.labels" (merge (dict "Labels" .Values.secret.labels) .) | nindent 4 }}
  {{- with $annotations := include "authelia.annotations" (merge (dict "Annotations" .Values.secret.annotations) .) }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
data:
  {{ .Values.configMap.access_control.secret.key }}: {{ tpl (.Files.Get "files/acl.yaml") . | trim | b64enc }}
{{- end }}