{{- if (include "authelia.generate.acl.secret" .) }}
---
{{- $yaml := tpl (.Files.Get "files/configuration.acl.yaml") . | trim }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "authelia.name.acl.secret" . }}
  labels: {{ include "authelia.labels" (merge (dict "Labels" .Values.secret.labels) .) | nindent 4 }}
  {{- with $annotations := include "authelia.annotations" (merge (dict "Annotations" .Values.secret.annotations) .) }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
data:
  {{ default "configuration.acl.yaml" .Values.configMap.access_control.secret.key }}: {{ (include "authelia.wrapYAML" $yaml) | b64enc }}
{{- end }}