#!/usr/bin/env bash

if [[ "${BUILDKITE_STEP_KEY}" == "index" ]]; then
  echo "--- :broom: Cleaning repository"

  rm -rf .cr-index
  mkdir .cr-index

  if [[ -n $(git branch --list gh-pages) ]]; then
    git branch --delete --force gh-pages
  fi

  git fetch --verbose --prune origin gh-pages
fi