#!/usr/bin/env bash

if [[ "${BUILDKITE_STEP_KEY}" == "index" ]]; then
  # Buildkite doesn't fetch the gh-pages branch when when the commit is against master so we need to do this for CR.
  echo "--- :fork: Fetching repository branch gh-pages"

  git fetch --verbose --prune origin gh-pages
fi