#!/usr/bin/env bash

set -eu

if [[ $BUILDKITE_LABEL == ":k8s: Publish Chart Index (Chart Releaser)" ]]; then
  echo "--- :tada: Configuring git user"

  git config user.name "James Elliott"
  git config user.email "james-d-elliott@users.noreply.github.com"
fi
